language: python
python:
  - "3.5"
os:
  - linux
before_install:
  - pushd .bins
  - wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha6/premake-5.0.0-alpha6-src.zip
  - wget https://github.com/martine/ninja/releases/download/v1.6.0/ninja-linux.zip
  - unzip premake-5.0.0-alpha6-src.zip
  - unzip ninja-linux.zip
  - pushd premake-5.0.0-alpha6
  - pushd build/gmake.unix/
  - make
  - popd
  - cp bin/release/premake5 ../premake5
  - popd
  - chmod +x premake5
  - chmod +x ninja
  - ls -al
  - export PATH=$(pwd):$PATH
  - ./premake5 --help
  - ./ninja --help
  - popd
script:
  - pushd tests
  - python3 run_tests.py
