language: python
python:
  - "3.4"
os:
  - osx
before_script:
  - wget https://github.com/premake/premake-core/releases/download/v5.0.0-alpha5/premake-5.0.0-alpha5-macosx.tar.gz
  - wget https://github.com/martine/ninja/releases/download/v1.6.0/ninja-mac.zip
  - tar -xzvf premake-5.0.0-alpha5-macosx.tar.gz
  - unzip ninja-mac.zip
  - chmod -x premake5
  - chmod -x ninja
  - ls -al
  - export PATH=$(pwd):$PATH
  - ./premake5 --help
  - ./ninja --help
script:
  - cd tests
  - python3 run_tests.py
