language: python
python:
  - "3.4"
os:
  - linux
before_install:
  - mkdir .bins
  - cd .bins
  - wget https://github.com/premake/premake-core/archive/v5.0.0-alpha5.zip
  - wget https://github.com/martine/ninja/releases/download/v1.6.0/ninja-linux.zip
  - unzip v5.0.0-alpha5.zip
  - unzip ninja-linux.zip
  - cd premake-core-5.0.0-alpha5
  - make -f Bootstrap.mak $TRAVIS_OS_NAME
  - cp bin/release/premake5 ../premak5
  - cd ..
  - chmod +x premake5
  - chmod +x ninja
  - ls -al
  - export PATH=$(pwd):$PATH
  - ./premake5 --help
  - ./ninja --help
  - cd ..
script:
  - cd tests
  - python3 run_tests.py
